version: "3"
services:
  geth:
    image: ethereum/client-go:v1.8.3
    ports:
      - "30303:30303"
      - "8546:8546"
    volumes:
      - ./geth-data:/root/.ethereum
    command: "--ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins \"*\""
    restart: always
  ws-database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_CHARSET=utf8
      - MYSQL_DATABASE=eth-db
    volumes:
      - ./mysql-data:/var/lib/mysql
  ws-migration:
    build:
      context: ./migration
    command: ["rake", "db:migrate"]
    restart: on-failure
    depends_on:
      - ws-database
    environment:
      - RAILS_ENV=customized
      - HOST=ws-database
      - PORT=3306
      - DATABASE=eth-db
      - USERNAME=root
      - PASSWORD=my-secret-pw
  ws-rpc:
    build:
      context: .
      dockerfile: ./cmd/service/Dockerfile
    command:
      - rpc
      - --db.host
      - ws-database
    ports:
      - 5487:5487
    restart: always
    depends_on:
      - ws-database
      - ws-migration
  ws-proxy:
    build:
      context: .
      dockerfile: ./cmd/service/Dockerfile
    command:
      - proxy
      - --grpc.host
      - ws-rpc
    ports:
      - 8080:8080
    restart: always
  ws-indexer:
    build:
      context: .
      dockerfile: ./cmd/service/Dockerfile
    command:
      - indexer
      - --db.host
      - ws-database
      - --eth.host
      - 206.189.44.219 # this is geth from 55, we will use our own geth in docker when we got geth with up-to-date data.
      - --eth.port
      - "9546" # this is geth from 55, please remove this argument and `--eth-port` when we use our geth in docker
      - --listen
    restart: on-failure
    depends_on:
      - ws-database
      - ws-migration
      - geth
