version: "3"
services:
  eth-indexer-database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_CHARSET=utf8
      - MYSQL_DATABASE=eth-db
  eth-indexer-migration:
    build:
      context: ./migration
    command: ["rake", "db:migrate"]
    restart: on-failure
    depends_on:
      - eth-indexer-database
    environment:
      - RAILS_ENV=customized
      - HOST=eth-indexer-database
      - PORT=3306
      - DATABASE=eth-db
      - USERNAME=root
      - PASSWORD=my-secret-pw
  eth-indexer:
    build:
      context: .
      dockerfile: ./cmd/indexer/Dockerfile
    command:
      - indexer
      - --db.host
      - eth-indexer-database
      - --eth.host
      - host.docker.internal # geth --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*"
      - --start
      - "2000000"
      - --end
      - "2000100"
    restart: on-failure
    depends_on:
      - eth-indexer-database
      - eth-indexer-migration
